In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5877, 3102, 1264, 9149],
 [5877, 3102, 1264, 5369],
 [5877, 2008, 1264, 2258],
 [2382, 3683, 2047, 9804, 5156],
 [2382, 3683, 2047, 9804, 8170],
 [3297, 5877, 4981, 1264, 3286],
 [9304, 6277, 4046, 9804]]

In [7]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np


In [9]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 5877 3102 1264 9149]
 [   0    0    0    0 5877 3102 1264 5369]
 [   0    0    0    0 5877 2008 1264 2258]
 [   0    0    0 2382 3683 2047 9804 5156]
 [   0    0    0 2382 3683 2047 9804 8170]
 [   0    0    0 3297 5877 4981 1264 3286]
 [   0    0    0    0 9304 6277 4046 9804]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_doc)

1/1 [==============================] - 0s 252ms/step


array([[[-0.04717269, -0.03266106, -0.00714137,  0.02677617,
         -0.00453557, -0.03257325,  0.03427113,  0.01027739,
         -0.00137093,  0.02560762],
        [-0.04717269, -0.03266106, -0.00714137,  0.02677617,
         -0.00453557, -0.03257325,  0.03427113,  0.01027739,
         -0.00137093,  0.02560762],
        [-0.04717269, -0.03266106, -0.00714137,  0.02677617,
         -0.00453557, -0.03257325,  0.03427113,  0.01027739,
         -0.00137093,  0.02560762],
        [-0.04717269, -0.03266106, -0.00714137,  0.02677617,
         -0.00453557, -0.03257325,  0.03427113,  0.01027739,
         -0.00137093,  0.02560762],
        [ 0.04530161,  0.00093113,  0.03905619, -0.02030453,
          0.0306637 , -0.01458398, -0.01597912, -0.00978223,
          0.03902144,  0.01690353],
        [ 0.04257757, -0.04557773,  0.04594269,  0.03972781,
         -0.00434542,  0.00469602,  0.02212992,  0.0458811 ,
          0.00542665,  0.02392104],
        [ 0.03257426,  0.01339274, -0.02378855, -0.0

In [14]:
print(embedded_doc[0])
print(embedded_doc[1])

[   0    0    0    0 5877 3102 1264 9149]
[   0    0    0    0 5877 3102 1264 5369]


In [15]:
model.predict(embedded_doc[0])

1/1 [==============================] - 0s 45ms/step


array([[-0.04717269, -0.03266106, -0.00714137,  0.02677617, -0.00453557,
        -0.03257325,  0.03427113,  0.01027739, -0.00137093,  0.02560762],
       [-0.04717269, -0.03266106, -0.00714137,  0.02677617, -0.00453557,
        -0.03257325,  0.03427113,  0.01027739, -0.00137093,  0.02560762],
       [-0.04717269, -0.03266106, -0.00714137,  0.02677617, -0.00453557,
        -0.03257325,  0.03427113,  0.01027739, -0.00137093,  0.02560762],
       [-0.04717269, -0.03266106, -0.00714137,  0.02677617, -0.00453557,
        -0.03257325,  0.03427113,  0.01027739, -0.00137093,  0.02560762],
       [ 0.04530161,  0.00093113,  0.03905619, -0.02030453,  0.0306637 ,
        -0.01458398, -0.01597912, -0.00978223,  0.03902144,  0.01690353],
       [ 0.04257757, -0.04557773,  0.04594269,  0.03972781, -0.00434542,
         0.00469602,  0.02212992,  0.0458811 ,  0.00542665,  0.02392104],
       [ 0.03257426,  0.01339274, -0.02378855, -0.03581729,  0.03767897,
         0.04353816, -0.04782473, -0.04800366